//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEST_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waypoint
    {
        public int Id { get; set; }
        public string WaypointName { get; set; }
        public Nullable<int> NextWaypointId { get; set; }
        public bool WasSkipped { get; set; }
        public Nullable<System.DateTime> TimeCompleted { get; set; }
        public string Action { get; set; }
        public string GeneratedBy { get; set; }
        public Nullable<int> MissionId { get; set; }
        public bool IsActive { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public double Altitude { get; set; }
    
        public virtual Waypoint NextWaypoint { get; set; }
        public virtual Mission Missions { get; set; }
    }
}
